name: Deploy DAB to dev

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Create ~/.databrickscfg
        run: |
          rm -f ~/.databrickscfg
          echo "[DEFAULT]" > ~/.databrickscfg
          echo "host = $DATABRICKS_HOST" >> ~/.databrickscfg
          echo "auth_type = client" >> ~/.databrickscfg
          echo "client_id = $DATABRICKS_CLIENT_ID" >> ~/.databrickscfg
          echo "client_secret = $DATABRICKS_CLIENT_SECRET" >> ~/.databrickscfg

      - name: Validate bundle for dev
        run: |
          databricks bundle validate -t dev

      - name: Deploy bundle to dev
        run: |
          databricks bundle deploy -t dev
